Ext.define('Tocadobicho.store.Lojas',{
    extend:'Ext.data.Store',

    config:{
        model:'Tocadobicho.model.Loja',
        data:[
            {
                id:1,
                produto:'ACTONEL',
                descricao:'RISEDRONATO SODICO',
                preco:45.37
            },
            {
                id:2,
                produto:'ACTONEL',
                descricao:'RISEDRONATO SODICO',
                preco:90.75
            },
            {
                id:3,
                produto:'ACTONEL',
                descricao:'RISEDRONATO SODICO',
                preco:81.49
            },
            {
                id:4,
                produto:'ACULAR',
                descricao:'TROMETAMOL CETOROLACO',
                preco:22.08
            },
            {
                id:5,
                produto:'ACULAR',
                descricao:'TROMETAMOL CETOROLACO',
                preco:20.21
            },
            {
                id:6,
                produto:'ADVIL',
                descricao:'IBUPROFENO',
                preco:9.07
            },
            {
                id:7,
                produto:'ADVIL',
                descricao:'IBUPROFENO',
                preco:7.24
            },
            {
                id:8,
                produto:'ADVIL',
                descricao:'IBUPROFENO',
                preco:7.57
            },
            {
                id:9,
                produto:'ADVIL',
                descricao:'IBUPROFENO',
                preco:7.94
            },
            {
                id:10,
                produto:'ADVIL',
                descricao:'IBUPROFENO',
                preco:6.93
            },
            {
                id:11,
                produto:'AEROFLUX',
                descricao:'SULFATO DE SALBUTAMOL + GUAIFENESINA',
                preco:5.65
            },
            {
                id:12,
                produto:'AEROFLUX',
                descricao:'SULFATO DE SALBUTAMOL + GUAIFENESINA',
                preco:5.65
            },
            {
                id:13,
                produto:'AEROLIN',
                descricao:'SULFATO DE SALBUTAMOL',
                preco:3.25
            },
            {
                id:14,
                produto:'AFRIN',
                descricao:'CLORIDRATO DE OXIMETAZOLINA',
                preco:7.53
            },
            {
                id:15,
                produto:'AFRIN',
                descricao:'CLORIDRATO DE OXIMETAZOLINA',
                preco:4.2
            },
            {
                id:16,
                produto:'AFRIN',
                descricao:'CLORIDRATO DE OXIMETAZOLINA',
                preco:5.23
            },
            {
                id:17,
                produto:'AFRIN',
                descricao:'CLORIDRATO DE OXIMETAZOLINA',
                preco:7.52
            },
            {
                id:18,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:10.58
            },
            {
                id:19,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:16.92
            },
            {
                id:20,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:17.13
            },
            {
                id:21,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:11.72
            },
            {
                id:22,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:11.99
            },
            {
                id:23,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:21.82
            },
            {
                id:24,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:17.15
            },
            {
                id:25,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:10.66
            },
            {
                id:26,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:22.54
            },
            {
                id:27,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:12.44
            },
            {
                id:28,
                produto:'ALDACTONE',
                descricao:'ESPIRONOLACTONA',
                preco:10.9
            },
            {
                id:29,
                produto:'ALDARA',
                descricao:'IMIQUIMODE',
                preco:63.57
            },
            {
                id:30,
                produto:'ALDARA',
                descricao:'IMIQUIMODE',
                preco:127.16
            },
            {
                id:31,
                produto:'ALDOMET',
                descricao:'METILDOPA',
                preco:20.02
            },
            {
                id:32,
                produto:'ALDOMET',
                descricao:'METILDOPA',
                preco:10.44
            },
            {
                id:33,
                produto:'ALDOMET',
                descricao:'METILDOPA',
                preco:20.85
            },
            {
                id:34,
                produto:'ALDOMET',
                descricao:'METILDOPA',
                preco:11.19
            },
            {
                id:35,
                produto:'ALIVIUM',
                descricao:'IBUPROFENO',
                preco:8.56
            },
            {
                id:36,
                produto:'ALIVIUM',
                descricao:'IBUPROFENO',
                preco:7.34
            },
            {
                id:37,
                produto:'ALIVIUM',
                descricao:'IBUPROFENO',
                preco:6.97
            },
            {
                id:38,
                produto:'ALIVIUM',
                descricao:'IBUPROFENO',
                preco:7.08
            },
            {
                id:39,
                produto:'ALIVIUM',
                descricao:'IBUPROFENO',
                preco:10.73
            },
            {
                id:40,
                produto:'ALIVIUM',
                descricao:'IBUPROFENO',
                preco:6.6
            },
            {
                id:41,
                produto:'ALIVIUM',
                descricao:'IBUPROFENO',
                preco:8.75
            },
            {
                id:42,
                produto:'ALPHAGAN',
                descricao:'TARTARATO DE BRIMONIDINA',
                preco:31.98
            },
            {
                id:43,
                produto:'ALPHAGAN',
                descricao:'TARTARATO DE BRIMONIDINA',
                preco:27.06
            },
            {
                id:44,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:39.51
            },
            {
                id:45,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:37.23
            },
            {
                id:46,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:12.18
            },
            {
                id:47,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:11.84
            },
            {
                id:48,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:34.07
            },
            {
                id:49,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:19.63
            },
            {
                id:50,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:57.82
            },
            {
                id:51,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:37.27
            },
            {
                id:52,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:66.93
            },
            {
                id:53,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:20.6
            },
            {
                id:54,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:36.19
            },
            {
                id:55,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:18.68
            },
            {
                id:56,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:36.13
            },
            {
                id:57,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:18.69
            },
            {
                id:58,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:12.52
            },
            {
                id:59,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:41.92
            },
            {
                id:60,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:70.91
            },
            {
                id:61,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:24.15
            },
            {
                id:62,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:41.92
            },
            {
                id:63,
                produto:'AMARYL',
                descricao:'GLIMEPIRIDA',
                preco:13.91
            },
            {
                id:64,
                produto:'AMINOFILINA',
                descricao:'AMINOFILINA',
                preco:2.92
            },
            {
                id:65,
                produto:'AMINOFILINA',
                descricao:'AMINOFILINA',
                preco:2.57
            },
            {
                id:66,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:13.77
            },
            {
                id:67,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:8.93
            },
            {
                id:68,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:12.3
            },
            {
                id:69,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:18.02
            },
            {
                id:70,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:8.74
            },
            {
                id:71,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:11.46
            },
            {
                id:72,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:26.57
            },
            {
                id:73,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:15.32
            },
            {
                id:74,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:10.06
            },
            {
                id:75,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:13.59
            },
            {
                id:76,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:29.48
            },
            {
                id:77,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:16.33
            },
            {
                id:78,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:13.15
            },
            {
                id:79,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:10.91
            },
            {
                id:80,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:16.03
            },
            {
                id:81,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:6.41
            },
            {
                id:82,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:17.79
            },
            {
                id:83,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:15.2
            },
            {
                id:84,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:21.05
            },
            {
                id:85,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:13.32
            },
            {
                id:86,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:7.38
            },
            {
                id:87,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:23.74
            },
            {
                id:88,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:17.78
            },
            {
                id:89,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:26.66
            },
            {
                id:90,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:18.76
            },
            {
                id:91,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:23.91
            },
            {
                id:92,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:16.88
            },
            {
                id:93,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:9.57
            },
            {
                id:94,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:17.27
            },
            {
                id:95,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:18.94
            },
            {
                id:96,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:15.63
            },
            {
                id:97,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:26.01
            },
            {
                id:98,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:17.32
            },
            {
                id:99,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:29.28
            },
            {
                id:100,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:26.71
            },
            {
                id:101,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:15.48
            },
            {
                id:102,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:25.17
            },
            {
                id:103,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:21.45
            },
            {
                id:104,
                produto:'AMOXIL',
                descricao:'AMOXICILINA',
                preco:19.75
            },
            {
                id:105,
                produto:'AMPLACILINA',
                descricao:'AMPICILINA',
                preco:25.84
            },
            {
                id:106,
                produto:'AMPLACILINA',
                descricao:'AMPICILINA',
                preco:9.45
            },
            {
                id:107,
                produto:'ANAFRANIL',
                descricao:'CLORIDRATO CLOMIPRAMINA',
                preco:12.71
            },
            {
                id:108,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:14.61
            },
            {
                id:109,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:4.84
            },
            {
                id:110,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:29.98
            },
            {
                id:111,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:23
            },
            {
                id:112,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:12.68
            },
            {
                id:113,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:6.82
            },
            {
                id:114,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:14.67
            },
            {
                id:115,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:28.19
            },
            {
                id:116,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:7.73
            },
            {
                id:117,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:18.2
            },
            {
                id:118,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:17.59
            },
            {
                id:119,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:32.97
            },
            {
                id:120,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:17.09
            },
            {
                id:121,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:15.46
            },
            {
                id:122,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:8.14
            },
            {
                id:123,
                produto:'ANTAK',
                descricao:'CLORIDRATO DE RANITIDINA',
                preco:15.65
            },
            {
                id:124,
                produto:'AROPAX',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:74.7
            },
            {
                id:125,
                produto:'AROPAX (GLAXOSMITHKLINE)',
                descricao:'MORATUS',
                preco:18.92
            },
            {
                id:126,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:51.18
            },
            {
                id:127,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:63.81
            },
            {
                id:128,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:45.46
            },
            {
                id:129,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:55.18
            },
            {
                id:130,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:43.54
            },
            {
                id:131,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:55.18
            },
            {
                id:132,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:66.47
            },
            {
                id:133,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:43.1
            },
            {
                id:134,
                produto:'AROPAX / CEBRILIN',
                descricao:'CLORIDRATO DE PAROXETINA',
                preco:58.05
            },
            {
                id:135,
                produto:'ASALIT',
                descricao:'MESALAZINA',
                preco:19.19
            },
            {
                id:136,
                produto:'ASPIRINA',
                descricao:'ACIDO ACETILSALICILICO',
                preco:26.21
            },
            {
                id:137,
                produto:'ASPIRINA INFANTIL',
                descricao:'ACIDO ACETILSALICILICO',
                preco:4.32
            },
            {
                id:138,
                produto:'ASPIRINA INFANTIL',
                descricao:'ACIDO ACETILSALICILICO',
                preco:0
            },
            {
                id:139,
                produto:'ASPIRINA INFANTIL',
                descricao:'ACIDO ACETILSALICILICO',
                preco:27.42
            },
            {
                id:140,
                produto:'ASPIRINA PREVENT',
                descricao:'ACIDO ACETILSALICILICO',
                preco:17.81
            },
            {
                id:141,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:10.37
            },
            {
                id:142,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:18.44
            },
            {
                id:143,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:7.84
            },
            {
                id:144,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:7.24
            },
            {
                id:145,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:10.2
            },
            {
                id:146,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:17.75
            },
            {
                id:147,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:19.63
            },
            {
                id:148,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:6.97
            },
            {
                id:149,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:12.74
            },
            {
                id:150,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:22.96
            },
            {
                id:151,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:14.97
            },
            {
                id:152,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:12.58
            },
            {
                id:153,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:40.81
            },
            {
                id:154,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:22.29
            },
            {
                id:155,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:23.69
            },
            {
                id:156,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:13.84
            },
            {
                id:157,
                produto:'ATENOL',
                descricao:'ATENOLOL',
                preco:8.32
            },
            {
                id:158,
                produto:'ATLANSIL',
                descricao:'CLORIDRATO DE AMIODARONA',
                preco:12.61
            },
            {
                id:159,
                produto:'ATLANSIL',
                descricao:'CLORIDRATO DE AMIODARONA',
                preco:6.6
            },
            {
                id:160,
                produto:'ATLANSIL',
                descricao:'CLORIDRATO DE AMIODARONA',
                preco:9.65
            },
            {
                id:161,
                produto:'ATLANSIL',
                descricao:'CLORIDRATO DE AMIODARONA',
                preco:18.42
            },
            {
                id:162,
                produto:'ATROVENT',
                descricao:'BROMETO DE IPRATROPIO',
                preco:7.36
            },
            {
                id:163,
                produto:'ATROVENT',
                descricao:'BROMETO DE IPRATROPIO',
                preco:7.36
            },
            {
                id:164,
                produto:'ATROVENT',
                descricao:'BROMETO DE IPRATROPIO',
                preco:7.03
            },
            {
                id:165,
                produto:'AZI E3S',
                descricao:'AZITROMICINA',
                preco:12.33
            },
            {
                id:166,
                produto:'BACTRIM',
                descricao:'SULFAMETOXAZOL + TRIMETOPRIMA',
                preco:6.68
            },
            {
                id:167,
                produto:'BACTRIM',
                descricao:'SULFAMETOXAZOL + TRIMETOPRIMA',
                preco:6.7
            },
            {
                id:168,
                produto:'BACTRIM',
                descricao:'SULFAMETOXAZOL + TRIMETOPRIMA',
                preco:8.53
            },
            {
                id:169,
                produto:'BACTRIM',
                descricao:'SULFAMETOXAZOL + TRIMETOPRIMA',
                preco:6.83
            },
            {
                id:170,
                produto:'BAYCUTEN N',
                descricao:'CLOTRIMAZOL + ACETATO DE DEXAMETASONA',
                preco:12.06
            },
            {
                id:171,
                produto:'BAYCUTEN N',
                descricao:'CLOTRIMAZOL + ACETATO DE DEXAMETASONA',
                preco:13.09
            },
            {
                id:172,
                produto:'BERLISON',
                descricao:'ACETATO DE HIDROCORTISONA',
                preco:9.42
            },
            {
                id:173,
                produto:'BERLISON',
                descricao:'ACETATO DE HIDROCORTISONA',
                preco:5.23
            },
            {
                id:174,
                produto:'BEROTEC',
                descricao:'BROMIDRATO DE FENOTEROL',
                preco:1.95
            },
            {
                id:175,
                produto:'BEROTEC',
                descricao:'BROMIDRATO DE FENOTEROL',
                preco:2.51
            },
            {
                id:176,
                produto:'BETNOVATE',
                descricao:'VALERATO DE BETAMETASONA',
                preco:0
            },
            {
                id:177,
                produto:'BETNOVATE',
                descricao:'VALERATO DE BETAMETASONA',
                preco:19.34
            },
            {
                id:178,
                produto:'BETNOVATE',
                descricao:'VALERATO DE BETAMETASONA',
                preco:11.88
            },
            {
                id:179,
                produto:'BETNOVATE',
                descricao:'VALERATO DE BETAMETASONA',
                preco:11.34
            },
            {
                id:180,
                produto:'BETNOVATE',
                descricao:'VALERATO DE BETAMETASONA',
                preco:10.2
            },
            {
                id:181,
                produto:'BETNOVATE',
                descricao:'VALERATO DE BETAMETASONA',
                preco:12.61
            },
            {
                id:182,
                produto:'BETNOVATE',
                descricao:'VALERATO DE BETAMETASONA',
                preco:12.02
            },
            {
                id:183,
                produto:'BIAMOTIL',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:8.04
            },
            {
                id:184,
                produto:'BIAMOTIL',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:7.71
            },
            {
                id:185,
                produto:'BIAMOTIL D ALL',
                descricao:'CLORIDRATO DE CIPROFLOXACINO + DEXAMETASONA',
                preco:13.45
            },
            {
                id:186,
                produto:'BIAMOTIL D ALL',
                descricao:'CLORIDRATO DE CIPROFLOXACINO + DEXAMETASONA',
                preco:13.45
            },
            {
                id:187,
                produto:'BINOTAL',
                descricao:'AMPICILINA',
                preco:6.92
            },
            {
                id:188,
                produto:'BINOTAL',
                descricao:'AMPICILINA',
                preco:27.01
            },
            {
                id:189,
                produto:'BINOTAL',
                descricao:'AMPICILINA',
                preco:13.83
            },
            {
                id:190,
                produto:'BISOLVON',
                descricao:'CLORIDRATO DE BROMEXINA',
                preco:5.25
            },
            {
                id:191,
                produto:'BISOLVON',
                descricao:'CLORIDRATO DE BROMEXINA',
                preco:7.51
            },
            {
                id:192,
                produto:'BISOLVON',
                descricao:'CLORIDRATO DE BROMEXINA',
                preco:5.57
            },
            {
                id:193,
                produto:'BISOLVON',
                descricao:'CLORIDRATO DE BROMEXINA',
                preco:8.12
            },
            {
                id:194,
                produto:'BISOLVON',
                descricao:'CLORIDRATO DE BROMEXINA',
                preco:10.44
            },
            {
                id:195,
                produto:'BRICANYL',
                descricao:'SULFATO DE TERBUTALINA',
                preco:6.28
            },
            {
                id:196,
                produto:'BRICANYL',
                descricao:'SULFATO DE TERBUTALINA',
                preco:6.35
            },
            {
                id:197,
                produto:'BRISMUCOL',
                descricao:'ACEBROFILINA',
                preco:10.76
            },
            {
                id:198,
                produto:'BRISMUCOL',
                descricao:'ACEBROFILINA',
                preco:15.18
            },
            {
                id:199,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:9.82
            },
            {
                id:200,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:10.12
            },
            {
                id:201,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:14.31
            },
            {
                id:202,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:10.13
            },
            {
                id:203,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:13.89
            },
            {
                id:204,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:13.99
            },
            {
                id:205,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:14.3
            },
            {
                id:206,
                produto:'BRISMUCOL / BRONDILAT',
                descricao:'ACEBROFILINA',
                preco:10.27
            },
            {
                id:207,
                produto:'BUSCOPAN',
                descricao:'BUTILBROMETO DE ESCOPOLAMINA',
                preco:5.47
            },
            {
                id:208,
                produto:'BUSCOPAN COMPOSTO',
                descricao:'BUTILBROMETO DE ESCOPOLAMINA + DIPIRONA SODICA',
                preco:5.11
            },
            {
                id:209,
                produto:'CAFAMOX',
                descricao:'CEFADROXIL',
                preco:29.29
            },
            {
                id:210,
                produto:'CAFAMOX',
                descricao:'CEFADROXIL',
                preco:21.82
            },
            {
                id:211,
                produto:'CALCORT',
                descricao:'DEFLAZACORTE',
                preco:22.6
            },
            {
                id:212,
                produto:'CALCORT',
                descricao:'DEFLAZACORTE',
                preco:53.97
            },
            {
                id:213,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:11.9
            },
            {
                id:214,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:11.63
            },
            {
                id:215,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:10.37
            },
            {
                id:216,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:10.61
            },
            {
                id:217,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:12
            },
            {
                id:218,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:12.14
            },
            {
                id:219,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:16
            },
            {
                id:220,
                produto:'CANDICORT',
                descricao:'CETOCONAZOL + DIPROPIONATO DE BETAMETASONA',
                preco:15.67
            },
            {
                id:221,
                produto:'CANESTEN',
                descricao:'CLOTRIMAZOL',
                preco:6.28
            },
            {
                id:222,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:29.57
            },
            {
                id:223,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:11.13
            },
            {
                id:224,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:42.29
            },
            {
                id:225,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:18.31
            },
            {
                id:226,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:23.73
            },
            {
                id:227,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:11.35
            },
            {
                id:228,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:7.84
            },
            {
                id:229,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:14.8
            },
            {
                id:230,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:47.59
            },
            {
                id:231,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:32.79
            },
            {
                id:232,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:32.94
            },
            {
                id:233,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:25.36
            },
            {
                id:234,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:24.1
            },
            {
                id:235,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:38.04
            },
            {
                id:236,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:16.22
            },
            {
                id:237,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:14.13
            },
            {
                id:238,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:17.25
            },
            {
                id:239,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:9.93
            },
            {
                id:240,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:11.24
            },
            {
                id:241,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:13.04
            },
            {
                id:242,
                produto:'CAPOTEN',
                descricao:'CAPTOPRIL',
                preco:29.23
            },
            {
                id:243,
                produto:'CARDIZEM',
                descricao:'CLORIDRATO DE DILTIAZEM',
                preco:16.75
            },
            {
                id:244,
                produto:'CARDIZEM',
                descricao:'CLORIDRATO DE DILTIAZEM',
                preco:8.78
            },
            {
                id:245,
                produto:'CARDIZEM',
                descricao:'CLORIDRATO DE DILTIAZEM',
                preco:8.79
            },
            {
                id:246,
                produto:'CARDIZEM',
                descricao:'CLORIDRATO DE DILTIAZEM',
                preco:10.44
            },
            {
                id:247,
                produto:'CARDIZEM',
                descricao:'CLORIDRATO DE DILTIAZEM',
                preco:16.88
            },
            {
                id:248,
                produto:'CARDIZEM',
                descricao:'CLORIDRATO DE DILTIAZEM',
                preco:5.32
            },
            {
                id:249,
                produto:'CARDIZEM',
                descricao:'CLORIDRATO DE DILTIAZEM',
                preco:8.59
            },
            {
                id:250,
                produto:'CARDURAN',
                descricao:'MESILATO DE DOXAZOSINA',
                preco:29.46
            },
            {
                id:251,
                produto:'CARDURAN',
                descricao:'MESILATO DE DOXAZOSINA',
                preco:41.18
            },
            {
                id:252,
                produto:'CARDURAN',
                descricao:'MESILATO DE DOXAZOSINA',
                preco:34.29
            },
            {
                id:253,
                produto:'CARDURAN',
                descricao:'MESILATO DE DOXAZOSINA',
                preco:41.18
            },
            {
                id:254,
                produto:'CARDURAN',
                descricao:'MESILATO DE DOXAZOSINA',
                preco:43.78
            },
            {
                id:255,
                produto:'CARTRAX',
                descricao:'TIOCONAZOL + TINIDAZOL',
                preco:26.76
            },
            {
                id:256,
                produto:'CARTRAX',
                descricao:'TIOCONAZOL + TINIDAZOL',
                preco:23.31
            },
            {
                id:257,
                produto:'CARTRAX',
                descricao:'TIOCONAZOL + TINIDAZOL',
                preco:25.47
            },
            {
                id:258,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO POTASSICO',
                preco:8.7
            },
            {
                id:259,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO POTASSICO',
                preco:5.69
            },
            {
                id:260,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO RESINATO',
                preco:6.37
            },
            {
                id:261,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO RESINATO',
                preco:6.6
            },
            {
                id:262,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO POTASSICO',
                preco:8.32
            },
            {
                id:263,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO RESINATO',
                preco:6.1
            },
            {
                id:264,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO POTÃ?SSICO',
                preco:9.61
            },
            {
                id:265,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO RESINATO',
                preco:6.86
            },
            {
                id:266,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO RESINATO',
                preco:6.44
            },
            {
                id:267,
                produto:'CATAFLAM',
                descricao:'DICLOFENACO POTASSICO',
                preco:9.05
            },
            {
                id:268,
                produto:'CATAFLAM EMULGEL',
                descricao:'DICLOFENACO DIETILAMONIO',
                preco:7.2
            },
            {
                id:269,
                produto:'CATAFLAM EMULGEL',
                descricao:'DICLOFENACO DIETILAMONIO',
                preco:6.23
            },
            {
                id:270,
                produto:'CATAFLAM EMULGEL',
                descricao:'DICLOFENACO DIETILAMÃ”NIO',
                preco:9.26
            },
            {
                id:271,
                produto:'CATAFLAM EMULGEL',
                descricao:'DICLOFENACO DIETILAMONIO',
                preco:7.55
            },
            {
                id:272,
                produto:'CATAFLAM EMULGEL',
                descricao:'DICLOFENACO DIETILAMONIO',
                preco:8.86
            },
            {
                id:273,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:35.64
            },
            {
                id:274,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:47.32
            },
            {
                id:275,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:0
            },
            {
                id:276,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:17.94
            },
            {
                id:277,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:49.02
            },
            {
                id:278,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:33.01
            },
            {
                id:279,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:36.06
            },
            {
                id:280,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:42.66
            },
            {
                id:281,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:31.37
            },
            {
                id:282,
                produto:'CECLOR',
                descricao:'CEFACLOR',
                preco:40.12
            },
            {
                id:283,
                produto:'CEDUR',
                descricao:'BEZAFIBRATO',
                preco:14.32
            },
            {
                id:284,
                produto:'CEDUR',
                descricao:'BEZAFIBRATO',
                preco:13.62
            },
            {
                id:285,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:34.28
            },
            {
                id:286,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:57.21
            },
            {
                id:287,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:22.98
            },
            {
                id:288,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:63.91
            },
            {
                id:289,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:28.71
            },
            {
                id:290,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:32.19
            },
            {
                id:291,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:70.66
            },
            {
                id:292,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:34.14
            },
            {
                id:293,
                produto:'CEFAMOX',
                descricao:'CEFADROXILA',
                preco:30.32
            },
            {
                id:294,
                produto:'CELESTAMINE',
                descricao:'MALEATO DE DEXCLORFENIRAMINA + BETAMETASONA',
                preco:17.57
            },
            {
                id:295,
                produto:'CELESTAMINE',
                descricao:'MALEATO DE DEXCLORFENIRAMINA + BETAMETASONA',
                preco:12.35
            },
            {
                id:296,
                produto:'CELESTAMINE',
                descricao:'MALEATO DE DEXCLORFENIRAMINA + BETAMETASONA',
                preco:16.89
            },
            {
                id:297,
                produto:'CELESTAMINE',
                descricao:'MALEATO DE DEXCLORFENIRAMINA + BETAMETASONA',
                preco:13.15
            },
            {
                id:298,
                produto:'CELESTAMINE',
                descricao:'MALEATO DE DEXCLORFENIRAMINA + BETAMETASONA',
                preco:9.41
            },
            {
                id:299,
                produto:'CELESTONE',
                descricao:'BETAMETASONA',
                preco:9.72
            },
            {
                id:300,
                produto:'CELESTONE',
                descricao:'BETAMETASONA',
                preco:9.6
            },
            {
                id:301,
                produto:'CELESTONE',
                descricao:'BETAMETASONA',
                preco:6.89
            },
            {
                id:302,
                produto:'CELESTONE',
                descricao:'BETAMETASONA',
                preco:5.06
            },
            {
                id:303,
                produto:'CELESTONE',
                descricao:'BETAMETASONA',
                preco:10.32
            },
            {
                id:304,
                produto:'CIPRAMIL',
                descricao:'CITALOPRAM',
                preco:36.93
            },
            {
                id:305,
                produto:'CIPRAMIL',
                descricao:'CITALOPRAM',
                preco:72.53
            },
            {
                id:306,
                produto:'CIPRAMIL',
                descricao:'CITALOPRAM',
                preco:26.17
            },
            {
                id:307,
                produto:'CIPRAMIL',
                descricao:'CITALOPRAM',
                preco:52.71
            },
            {
                id:308,
                produto:'CIPRAMIL',
                descricao:'BROMIDRATO DE CITALOPRAM',
                preco:25.33
            },
            {
                id:309,
                produto:'CIPRAMIL',
                descricao:'BROMIDRATO DE CITALOPRAM',
                preco:67.19
            },
            {
                id:310,
                produto:'CIPRAMIL',
                descricao:'BROMIDRATO DE CITALOPRAM',
                preco:50.61
            },
            {
                id:311,
                produto:'CIPRAMIL',
                descricao:'CITALOPRAM',
                preco:27.97
            },
            {
                id:312,
                produto:'CIPRAMIL',
                descricao:'CITALOPRAM',
                preco:55.96
            },
            {
                id:313,
                produto:'CIPRAMIL LUN',
                descricao:'BROMIDRATO DE CITALOPRAM',
                preco:59.8
            },
            {
                id:314,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:0
            },
            {
                id:315,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:28.88
            },
            {
                id:316,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:57.92
            },
            {
                id:317,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:25.42
            },
            {
                id:318,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:19.22
            },
            {
                id:319,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:8.06
            },
            {
                id:320,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:25.9
            },
            {
                id:321,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:0
            },
            {
                id:322,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:28.88
            },
            {
                id:323,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:17.95
            },
            {
                id:324,
                produto:'CIPRO',
                descricao:'CLORIDRATO DE CIPROFLOXACINO',
                preco:20.44
            },
            {
                id:325,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CÃ?LCICA',
                preco:124.46
            },
            {
                id:326,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CÃ?LCICA',
                preco:67.39
            },
            {
                id:327,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CÃ?LCICA',
                preco:68.94
            },
            {
                id:328,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CÃ?LCICA',
                preco:124.46
            },
            {
                id:329,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:46.77
            },
            {
                id:330,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:32.55
            },
            {
                id:331,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:46.77
            },
            {
                id:332,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:32.55
            },
            {
                id:333,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:168.33
            },
            {
                id:334,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:93.53
            },
            {
                id:335,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:100.13
            },
            {
                id:336,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:100.13
            },
            {
                id:337,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:50.06
            },
            {
                id:338,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:50.06
            },
            {
                id:339,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:84.19
            },
            {
                id:340,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:84.19
            },
            {
                id:341,
                produto:'CITALOR',
                descricao:'ATORVASTATINA CALCICA',
                preco:93.53
            },
            {
                id:342,
                produto:'CLARIPEL',
                descricao:'HIDROQUINONA',
                preco:23.95
            },
            {
                id:343,
                produto:'CLARIPEL',
                descricao:'HIDROQUINONA',
                preco:23.95
            },
            {
                id:344,
                produto:'CLARIPEL',
                descricao:'HIDROQUINONA',
                preco:23.95
            },
            {
                id:345,
                produto:'CLARITIN',
                descricao:'LORATADINA',
                preco:18.01
            },
            {
                id:346,
                produto:'CLARITIN',
                descricao:'LORATADINA',
                preco:15.58
            },
            {
                id:347,
                produto:'CLARITIN',
                descricao:'LORATADINA',
                preco:14.48
            },
            {
                id:348,
                produto:'CLARITIN',
                descricao:'LORATADINA',
                preco:12.87
            },
            {
                id:349,
                produto:'CLARITIN',
                descricao:'LORATADINA',
                preco:15.18
            },
            {
                id:350,
                produto:'CLARITIN',
                descricao:'LORATADINA',
                preco:11.89
            },
            {
                id:351,
                produto:'CLARITIN D',
                descricao:'LORATADINA + SULFATO DE PSEUDOEFEDRINA',
                preco:14.6
            },
            {
                id:352,
                produto:'CLARITIN D',
                descricao:'LORATADINA + SULFATO DE PSEUDOEFEDRINA',
                preco:16.33
            },
            {
                id:353,
                produto:'CLARITIN D',
                descricao:'LORATADINA + SULFATO DE PSEUDOEFEDRINA',
                preco:14.69
            },
            {
                id:354,
                produto:'CLARITIN D',
                descricao:'LORATADINA + SULFATO DE PSEUDOEFEDRINA',
                preco:16.79
            },
            {
                id:355,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:58.67
            },
            {
                id:356,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:70.69
            },
            {
                id:357,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:41.59
            },
            {
                id:358,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:63.76
            },
            {
                id:359,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:41.59
            },
            {
                id:360,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:35.92
            },
            {
                id:361,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:53.74
            },
            {
                id:362,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:28.39
            },
            {
                id:363,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:70.69
            },
            {
                id:364,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:58.67
            },
            {
                id:365,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:97.78
            },
            {
                id:366,
                produto:'CLAVULIN',
                descricao:'AMOXICILINA  + CLAVULANATO DE POTASSIO',
                preco:41.26
            },
            {
                id:367,
                produto:'CLINAGEL',
                descricao:'FOSFATO DE CLINDAMICINA',
                preco:18.79
            },
            {
                id:368,
                produto:'CLORANA',
                descricao:'HIDROCLOROTIAZIDA',
                preco:3.23
            },
            {
                id:369,
                produto:'CLORANA',
                descricao:'HIDROCLOROTIAZIDA',
                preco:3.34
            },
            {
                id:370,
                produto:'CLORANA',
                descricao:'HIDROCLOROTIAZIDA',
                preco:3.21
            },
            {
                id:371,
                produto:'CLORANA',
                descricao:'HIDROCLOROTIAZIDA',
                preco:3.37
            },
            {
                id:372,
                produto:'CLORANA',
                descricao:'HIDROCLOROTIAZIDA',
                preco:3.54
            },
            {
                id:373,
                produto:'CLORIDATO DE TASULOSINA (GEOLAB)',
                descricao:'CLORIDRATO DE TANSULOSINA ',
                preco:94.76
            },
            {
                id:374,
                produto:'CO-RENITEC',
                descricao:'MALEATO DE ENALAPRIL + HIDROCLOROTIAZIDA',
                preco:15.36
            },
            {
                id:375,
                produto:'CO-RENITEC',
                descricao:'MALEATO DE ENALAPRIL + HIDROCLOROTIAZIDA',
                preco:35.73
            },
            {
                id:376,
                produto:'CO-RENITEC',
                descricao:'MALEATO DE ENALAPRIL + HIDROCLOROTIAZIDA',
                preco:22.32
            },
            {
                id:377,
                produto:'CO-RENITEC',
                descricao:'MALEATO DE ENALAPRIL + HIDROCLOROTIAZIDA',
                preco:22.44
            },
            {
                id:378,
                produto:'CO-RENITEC',
                descricao:'MALEATO DE ENALAPRIL + HIDROCLOROTIAZIDA',
                preco:38.28
            },
            {
                id:379,
                produto:'COLPISTATIN',
                descricao:'BENZOILMETRONIDAZOL + NISTATINA + CLORETO DE BENZALCÃ”NIO',
                preco:18.59
            },
            {
                id:380,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:21.53
            },
            {
                id:381,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:16.95
            },
            {
                id:382,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:18.18
            },
            {
                id:383,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:34.58
            },
            {
                id:384,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:25.43
            },
            {
                id:385,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:48.47
            },
            {
                id:386,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:26.24
            },
            {
                id:387,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:41.5
            },
            {
                id:388,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:70.14
            },
            {
                id:389,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:36.4
            },
            {
                id:390,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:18.74
            },
            {
                id:391,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:21.7
            },
            {
                id:392,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:15.58
            },
            {
                id:393,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:36.59
            },
            {
                id:394,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:12.07
            },
            {
                id:395,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:13.55
            },
            {
                id:396,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:16.11
            },
            {
                id:397,
                produto:'COREG',
                descricao:'CARVEDILOL',
                preco:20.33
            },
            {
                id:398,
                produto:'COSOPT',
                descricao:'CLORIDRATO DE DORZOLAMIDA + MALEATO DE TIMOLOL',
                preco:0
            },
            {
                id:399,
                produto:'COSOPT',
                descricao:'CLORIDRATO DE DORZOLAMIDA + MALEATO DE TIMOLOL',
                preco:42.68
            },
            {
                id:400,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:39.59
            },
            {
                id:401,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:41.98
            },
            {
                id:402,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:31.74
            },
            {
                id:403,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:31.74
            },
            {
                id:404,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:21.5
            },
            {
                id:405,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:9.47
            },
            {
                id:406,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:31.04
            },
            {
                id:407,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:18.94
            },
            {
                id:408,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:18.94
            },
            {
                id:409,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:21.5
            },
            {
                id:410,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:21.5
            },
            {
                id:411,
                produto:'COZAAR',
                descricao:'LOSARTANA POTASSICA',
                preco:21.51
            },
            {
                id:412,
                produto:'COZAAR',
                descricao:'LOSARTANA POTÃ?SSICA',
                preco:11.42
            },
            {
                id:413,
                produto:'COZAAR',
                descricao:'LOSARTANA POTÃ?SSICA',
                preco:22.87
            },
            {
                id:414,
                produto:'COZAAR',
                descricao:'LOSARTANA POTÃ?SSICA',
                preco:44.47
            },
            {
                id:415,
                produto:'COZAAR',
                descricao:'LOSARTANA POTÃ?SSICA',
                preco:33.74
            },
            {
                id:416,
                produto:'CRESTOR',
                descricao:'ROSUVASTATINA CALCICA',
                preco:107.88
            },
            {
                id:417,
                produto:'CRESTOR',
                descricao:'ROSUVASTATINA CALCICA',
                preco:57.6
            },
            {
                id:418,
                produto:'CRESTOR',
                descricao:'ROSUVASTATINA CALCICA',
                preco:61.59
            },
            {
                id:419,
                produto:'CRESTOR',
                descricao:'ROSUVASTATINA CALCICA',
                preco:107.88
            },
            {
                id:420,
                produto:'CRESTOR',
                descricao:'ROSUVASTATINA CALCICA',
                preco:100.89
            },
            {
                id:421,
                produto:'CRESTOR',
                descricao:'ROSUVASTATINA CALCICA',
                preco:61.59
            },
            {
                id:422,
                produto:'CRESTOR (ASTRAZENECA)',
                descricao:'ROSUVASTATINA CÃ?LCICA',
                preco:65.48
            },
            {
                id:423,
                produto:'CRESTOR (ASTRAZENECA)',
                descricao:'ROSUVASTATINA CÃ?LCICA',
                preco:114.71
            },
            {
                id:424,
                produto:'DAFORIN',
                descricao:'CLORIDRATO DE FLUOXETINA',
                preco:16.78
            },
            {
                id:425,
                produto:'DAFORIN',
                descricao:'CLORIDRATO DE FLUOXETINA',
                preco:21.44
            },
            {
                id:426,
                produto:'DAFORIN',
                descricao:'CLORIDRATO DE FLUOXETINA',
                preco:11.07
            },
            {
                id:427,
                produto:'DAFORIN',
                descricao:'CLORIDRATO DE FLUOXETINA',
                preco:15.58
            },
            {
                id:428,
                produto:'DAFORIN',
                descricao:'CLORIDRATO DE FLUOXETINA',
                preco:23.57
            },
            {
                id:429,
                produto:'DAFORIN',
                descricao:'CLORIDRATO DE FLUOXETINA',
                preco:15.54
            },
            {
                id:430,
                produto:'DAFORIN',
                descricao:'CLORIDRATO DE FLUOXETINA',
                preco:11.13
            },
            {
                id:431,
                produto:'DAKTARIN',
                descricao:'NITRATO DE MICONAZOL',
                preco:7.87
            },
            {
                id:432,
                produto:'DAKTARIN',
                descricao:'NITRATO DE MICONAZOL',
                preco:8.8
            },
            {
                id:433,
                produto:'DALACIN C',
                descricao:'CLORIDRATO DE CLINDAMICINA',
                preco:33.54
            },
            {
                id:434,
                produto:'DALACIN C',
                descricao:'CLORIDRATO DE CLINDAMICINA',
                preco:0
            },
            {
                id:435,
                produto:'DALACIN C',
                descricao:'CLORIDRATO DE CLINDAMICINA',
                preco:33.12
            },
            {
                id:436,
                produto:'DALACIN V',
                descricao:'FOSFATO DE CLINDAMICINA',
                preco:26.26
            },
            {
                id:437,
                produto:'DAONIL',
                descricao:'GLIBENCLAMIDA',
                preco:5.47
            },
            {
                id:438,
                produto:'DAONIL',
                descricao:'GLIBENCLAMIDA',
                preco:5.41
            },
            {
                id:439,
                produto:'DAONIL',
                descricao:'GLIBENCLAMIDA',
                preco:5.28
            },
            {
                id:440,
                produto:'DAONIL',
                descricao:'GLIBENCLAMIDA',
                preco:5.89
            },
            {
                id:441,
                produto:'DAONIL',
                descricao:'GLIBENCLAMIDA',
                preco:11.19
            },
            {
                id:442,
                produto:'DECADRON',
                descricao:'DEXAMETASONA',
                preco:8.21
            },
            {
                id:443,
                produto:'DECADRON',
                descricao:'DEXAMETASONA',
                preco:5.77
            },
            {
                id:444,
                produto:'DECADRON',
                descricao:'DEXAMETASONA',
                preco:5.77
            },
            {
                id:445,
                produto:'DECADRON',
                descricao:'DEXAMETASONA',
                preco:5.37
            },
            {
                id:446,
                produto:'DECADRON',
                descricao:'DEXAMETASONA',
                preco:5.78
            },
            {
                id:447,
                produto:'DECADRON',
                descricao:'DEXAMETASONA',
                preco:7.09
            },
            {
                id:448,
                produto:'DEPAKENE',
                descricao:'VALPROATO DE SODIO',
                preco:5.34
            },
            {
                id:449,
                produto:'DERMODEX',
                descricao:'NISTATINA + OXIDO DE ZINCO',
                preco:19.36
            },
            {
                id:450,
                produto:'DERMODEX',
                descricao:'NISTATINA + OXIDO DE ZINCO',
                preco:19.34
            },
            {
                id:451,
                produto:'DERMODEX',
                descricao:'NISTATINA + Ã“XIDO DE ZINCO',
                preco:21.01
            },
            {
                id:452,
                produto:'DERMOMAX',
                descricao:'LIDOCAINA',
                preco:37.41
            },
            {
                id:453,
                produto:'DERMOMAX',
                descricao:'LIDOCAINA',
                preco:41.62
            },
            {
                id:454,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:17.14
            },
            {
                id:455,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:17.14
            },
            {
                id:456,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:28.57
            },
            {
                id:457,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:51.41
            },
            {
                id:458,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:28.57
            },
            {
                id:459,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:21.42
            },
            {
                id:460,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:21.42
            },
            {
                id:461,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:30.38
            },
            {
                id:462,
                produto:'DESALEX',
                descricao:'DESLORATADINA',
                preco:18.23
            },
            {
                id:463,
                produto:'DESONOL',
                descricao:'DESONIDA',
                preco:15.86
            },
            {
                id:464,
                produto:'DESONOL',
                descricao:'DESONIDA',
                preco:14.21
            },
            {
                id:465,
                produto:'DESONOL',
                descricao:'DESONIDA',
                preco:14.36
            },
            {
                id:466,
                produto:'DESONOL',
                descricao:'DESONIDA',
                preco:14.56
            },
            {
                id:467,
                produto:'DESONOL/ADINOS',
                descricao:'DESONIDA',
                preco:16.03
            },
            {
                id:468,
                produto:'DEXASON',
                descricao:'ACETATO DE DEXAMETASONA',
                preco:4.42
            },
            {
                id:469,
                produto:'DEXASON',
                descricao:'ACETATO DE DEXAMETASONA',
                preco:4.46
            },
            {
                id:470,
                produto:'DEXASON',
                descricao:'ACETATO DE DEXAMETASONA',
                preco:4.46
            },
            {
                id:471,
                produto:'DIFFERIN',
                descricao:'ADAPALENO',
                preco:32.61
            },
            {
                id:472,
                produto:'DIFFERIN',
                descricao:'ADAPALENO',
                preco:31.57
            },
            {
                id:473,
                produto:'DIFFERIN',
                descricao:'ADAPALENO',
                preco:33.77
            },
            {
                id:474,
                produto:'DIFFERIN',
                descricao:'ADAPALENO',
                preco:29.49
            },
            {
                id:475,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:9.77
            },
            {
                id:476,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:12.44
            },
            {
                id:477,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:11.69
            },
            {
                id:478,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:9.24
            },
            {
                id:479,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:7.86
            },
            {
                id:480,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:9.13
            },
            {
                id:481,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:9.64
            },
            {
                id:482,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:10.31
            },
            {
                id:483,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:11.59
            },
            {
                id:484,
                produto:'DIGESAN',
                descricao:'BROMOPRIDA',
                preco:8.89
            },
            {
                id:485,
                produto:'DIGOXINA',
                descricao:'DIGOXINA',
                preco:7.12
            },
            {
                id:486,
                produto:'DILACORON',
                descricao:'CLORIDRATO DE VERAPAMIL',
                preco:17.99
            },
            {
                id:487,
                produto:'DILACORON',
                descricao:'CLORIDRATO DE VERAPAMIL',
                preco:11.07
            },
            {
                id:488,
                produto:'DILACORON',
                descricao:'CLORIDRATO DE VERAPAMIL',
                preco:13.25
            },
            {
                id:489,
                produto:'DILACORON',
                descricao:'CLORIDRATO DE VERAPAMIL',
                preco:11.72
            },
            {
                id:490,
                produto:'DILACORON',
                descricao:'CLORIDRATO DE VERAPAMIL',
                preco:35.32
            },
            {
                id:491,
                produto:'DILACORON',
                descricao:'CLORIDRATO DE VERAPAMIL',
                preco:12.36
            },
            {
                id:492,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:39.45
            },
            {
                id:493,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:22.58
            },
            {
                id:494,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:22.58
            },
            {
                id:495,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:22.58
            },
            {
                id:496,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:26.14
            },
            {
                id:497,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:31.56
            },
            {
                id:498,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:39.45
            },
            {
                id:499,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:54.09
            },
            {
                id:500,
                produto:'DIOVAN',
                descricao:'VALSARTANA',
                preco:99.45
            }
        ]
    }

})
